
services:
  my-client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: iangacheru/my-client:1.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - inet
    volumes:
      # Bind-mount client directory for development (adjust for production)
      - ./client:/usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]  
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: iangacheru/backend:1.0
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/mydatabase
    networks:
      - inet
    volumes:
      # Bind-mount backend directory for development (adjust for production)
      - ./backend:/usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"] 
      interval: 30s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:4.4.18-focal
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - inet
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  inet:
    driver: bridge

volumes:
  mongo-data:
