---
- name: Yolo project setup + provisioning ubuntu 
  hosts: all
  become: true
  vars_files:
    - ansible/vars/variables.yaml 

  tasks:
    - name: Update and Upgrade APT packages
      block:
        - name: Update APT package cache
          apt:
            update_cache: yes
        
        - name: Upgrade APT packages
          apt:
            upgrade: dist

    - name: Install necessary packages for Docker and Node.js
      block:
        - name: Install packages
          apt:
            name: "{{ packages }}"
            state: present
          loop: "{{ packages }}"  

    - name: Manage Docker service
      block:
        - name: Start Docker service
          service:
            name: docker
            state: started

        - name: Enable Docker service on boot
          service:
            name: docker
            enabled: true

    - name: Clone the YOLO repository
      block:
        - name: Clone the repository from GitHub
          git:
            repo: 'https://github.com/GacheruIan/yolo.git'
            dest: '/home/ubuntu/yolo'
            version: 'master'

    - name: Build and start Docker containers
      block:
        - name: Build and start containers using Docker Compose
          community.docker.docker_compose:
            project_src: /home/ubuntu/yolo
            restarted: true

    - name: Install project dependencies
      block:
        - name: Install client dependencies
          npm:
            path: /home/ubuntu/yolo/client
            state: present

        - name: Install backend dependencies
          npm:
            path: /home/ubuntu/yolo/backend
            state: present
