apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: iangacheru/backend:1.1  
        ports:
        - containerPort: 5000 
        env:
        - name: MONGODB_URI
          value: "MONGODB_URI: mongodb://mongo:27017/yolomy"  
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
