apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # expose my service on nodePort 30080
  type: NodePort  #  for easier access loadbalancer nope